### ISSUE TITLE
update uglifyjs

### ISSUE THREAD

**Issue by tc80** [cdnjs/tools#144]
seems [uglifyjs does not support es6](https://stackoverflow.com/questions/47439067/uglifyjs-throws-unexpected-token-keyword-const-with-node-modules), leaving to failed minification:

```
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]: 2020/07/29 16:33:21 a/aui.json: compress: run /cdnjs-sven/tools/node_modules/uglify-js/bin/uglifyjs --mangle --compress if_return=true -o /cdnjs-sven/cdnjs/ajax/libs/aui/9.0.2-alpha-1/aui/aui-prototyping.nodeps.min.js /cdnjs-sven/cdnjs/ajax/libs/aui/9.0.2-alpha-1/aui/aui-prototyping.nodeps.js
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]: 2020/07/29 16:33:21 a/aui.json: failed with exit status 1: Parse error at /cdnjs-sven/cdnjs/ajax/libs/aui/9.0.2-alpha-1/aui/aui-prototyping.nodeps.js:1,240973
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]: 5),i(36),i(37);var n=i(1),s=i.n(n),r=window.jQuery||window.Zepto||s.a;const o="A
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:                                                                       ^
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]: ERROR: Unexpected token: keyword «const»
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at JS_Parse_Error.get (eval at <anonymous> (/cdnjs-sven/tools/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:69:23)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at fatal (/cdnjs-sven/tools/node_modules/uglify-js/bin/uglifyjs:332:27)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at run (/cdnjs-sven/tools/node_modules/uglify-js/bin/uglifyjs:275:9)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at Object.<anonymous> (/cdnjs-sven/tools/node_modules/uglify-js/bin/uglifyjs:190:5)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Jul 29 16:33:21 cdnjs-bot-6 autoupdate[5151]:     at internal/main/run_main_module.js:18:47
```

**Comment by MattIPv4** [comment]
Should probably be replaced with terser

**Comment by tc80** [comment]
agreed. this should be fixed before we do our final big migration to KV so all js files are minified properly
