### ISSUE TITLE
autoupdate tries to add ignored files and panic

### ISSUE THREAD

**Issue by klausenbusk** [cdnjs/tools#58]
```
2020/07/01 23:36:31 a/agility.json: adding version 0.1.0-docs
2020/07/01 23:36:31 a/agility.json: run /usr/bin/git add /home/runner/work/cdnjs/cdnjs/cdnjs/ajax/libs/agility/0.1.0-docs
The following paths are ignored by one of your .gitignore files:
ajax/libs/agility/0.1.0-docs

panic: exit status 1

goroutine 1 [running]:
github.com/cdnjs/tools/util.CheckCmd(0xc000446c00, 0x5e, 0x600, 0x900ac0, 0xc00019c4c0, 0xc00019c4c0, 0xc0002f23d0)
	/home/runner/work/tools/tools/util/check.go:19 +0x137
github.com/cdnjs/tools/packages.GitAdd(0x907e40, 0xc00013cd50, 0xc0002735f0, 0x23, 0xc0003140c0, 0x40)
	/home/runner/work/tools/tools/packages/git.go:74 +0x199
main.commitNewVersions(0x907e40, 0xc00013cd50, 0xc0002fc990, 0x1, 0x1)
	/home/runner/work/tools/tools/cmd/autoupdate/main.go:195 +0x209
main.main()
	/home/runner/work/tools/tools/cmd/autoupdate/main.go:91 +0x49b
```
Quick and dirty fix: https://github.com/klausenbusk/tools/commit/78a8046471667bb8fa012ff445fd1c17b316a84b

**Comment by tc80** [comment]
This is a known problem, nice dirty fix!

@xtuc

**Comment by xtuc** [comment]
I actually like that fix, my other idea was just to remove the gitignore and push the version we didn't want

**Comment by klausenbusk** [comment]
Could you have a look at the PR?
